/*
  File autogenerated by gengetopt version 2.22.5
  generated with the following command:
  gengetopt --input=cmdline_dtspg.ggo -a gengetopt_args_info_dtspg -F cmdline_dtspg -a gengetopt_args_info_dtspg -F cmdline_dtspg

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline_dtspg.h"

const char *gengetopt_args_info_dtspg_purpose = "Solution of Toeplitz Linear Systems";

const char *gengetopt_args_info_dtspg_usage = "Usage: dtspg [OPTIONS]...";

const char *gengetopt_args_info_dtspg_description = "";

const char *gengetopt_args_info_dtspg_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "\nData source:",
  "  -n, --size=INT                Size of problem",
  "  -z, --block-size=INT          Block size",
  "  -b, --number-blocks=INT       Number of blocks",
  "      --toeplitz-file=STRING    File containing toeplitz vector values (set to \n                                  '-' to use standard input)",
  "      --toeplitz-random         Use random data of specified size as toeplitz \n                                  vector  (default=on)",
  "      --toeplitz-save-random=STRING\n                                File where random toeplitz data should be saved",
  "      --rhs-file=STRING         File containing rhs vector values (set to '-' \n                                  to use standard input)",
  "      --rhs-random              Use random data of specified size as rhs vector \n                                   (default=on)",
  "      --rhs-save-random=STRING  File where random rhs data should be saved",
  "      --random-seed=INT         Seed used to initialize random number generator \n                                  (allows repeatable tests)",
  "\nOutput options:",
  "      --time                    Show time spent in system resolution  \n                                  (default=on)",
  "      --show-results            Print system solution vector to standard output \n                                   (default=off)",
  "      --raw-results             Generates raw results for statistical graphics  \n                                  (default=off)",
  "      --raw-headers             Prints commented header (column info) for raw \n                                  results  (default=off)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info_dtspg *args_info);
static
void clear_args (struct gengetopt_args_info_dtspg *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info_dtspg *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info_dtspg *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info_dtspg *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->size_given = 0 ;
  args_info->block_size_given = 0 ;
  args_info->number_blocks_given = 0 ;
  args_info->toeplitz_file_given = 0 ;
  args_info->toeplitz_random_given = 0 ;
  args_info->toeplitz_save_random_given = 0 ;
  args_info->rhs_file_given = 0 ;
  args_info->rhs_random_given = 0 ;
  args_info->rhs_save_random_given = 0 ;
  args_info->random_seed_given = 0 ;
  args_info->time_given = 0 ;
  args_info->show_results_given = 0 ;
  args_info->raw_results_given = 0 ;
  args_info->raw_headers_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info_dtspg *args_info)
{
  FIX_UNUSED (args_info);
  args_info->size_orig = NULL;
  args_info->block_size_orig = NULL;
  args_info->number_blocks_orig = NULL;
  args_info->toeplitz_file_arg = NULL;
  args_info->toeplitz_file_orig = NULL;
  args_info->toeplitz_random_flag = 1;
  args_info->toeplitz_save_random_arg = NULL;
  args_info->toeplitz_save_random_orig = NULL;
  args_info->rhs_file_arg = NULL;
  args_info->rhs_file_orig = NULL;
  args_info->rhs_random_flag = 1;
  args_info->rhs_save_random_arg = NULL;
  args_info->rhs_save_random_orig = NULL;
  args_info->random_seed_orig = NULL;
  args_info->time_flag = 1;
  args_info->show_results_flag = 0;
  args_info->raw_results_flag = 0;
  args_info->raw_headers_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info_dtspg *args_info)
{


  args_info->help_help = gengetopt_args_info_dtspg_help[0] ;
  args_info->version_help = gengetopt_args_info_dtspg_help[1] ;
  args_info->size_help = gengetopt_args_info_dtspg_help[3] ;
  args_info->block_size_help = gengetopt_args_info_dtspg_help[4] ;
  args_info->number_blocks_help = gengetopt_args_info_dtspg_help[5] ;
  args_info->toeplitz_file_help = gengetopt_args_info_dtspg_help[6] ;
  args_info->toeplitz_random_help = gengetopt_args_info_dtspg_help[7] ;
  args_info->toeplitz_save_random_help = gengetopt_args_info_dtspg_help[8] ;
  args_info->rhs_file_help = gengetopt_args_info_dtspg_help[9] ;
  args_info->rhs_random_help = gengetopt_args_info_dtspg_help[10] ;
  args_info->rhs_save_random_help = gengetopt_args_info_dtspg_help[11] ;
  args_info->random_seed_help = gengetopt_args_info_dtspg_help[12] ;
  args_info->time_help = gengetopt_args_info_dtspg_help[14] ;
  args_info->show_results_help = gengetopt_args_info_dtspg_help[15] ;
  args_info->raw_results_help = gengetopt_args_info_dtspg_help[16] ;
  args_info->raw_headers_help = gengetopt_args_info_dtspg_help[17] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_dtspg_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_dtspg_purpose);

  if (strlen(gengetopt_args_info_dtspg_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_dtspg_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_dtspg_description) > 0)
    printf("%s\n\n", gengetopt_args_info_dtspg_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_dtspg_help[i])
    printf("%s\n", gengetopt_args_info_dtspg_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info_dtspg *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info_dtspg *args_info)
{

  free_string_field (&(args_info->size_orig));
  free_string_field (&(args_info->block_size_orig));
  free_string_field (&(args_info->number_blocks_orig));
  free_string_field (&(args_info->toeplitz_file_arg));
  free_string_field (&(args_info->toeplitz_file_orig));
  free_string_field (&(args_info->toeplitz_save_random_arg));
  free_string_field (&(args_info->toeplitz_save_random_orig));
  free_string_field (&(args_info->rhs_file_arg));
  free_string_field (&(args_info->rhs_file_orig));
  free_string_field (&(args_info->rhs_save_random_arg));
  free_string_field (&(args_info->rhs_save_random_orig));
  free_string_field (&(args_info->random_seed_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info_dtspg *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->size_given)
    write_into_file(outfile, "size", args_info->size_orig, 0);
  if (args_info->block_size_given)
    write_into_file(outfile, "block-size", args_info->block_size_orig, 0);
  if (args_info->number_blocks_given)
    write_into_file(outfile, "number-blocks", args_info->number_blocks_orig, 0);
  if (args_info->toeplitz_file_given)
    write_into_file(outfile, "toeplitz-file", args_info->toeplitz_file_orig, 0);
  if (args_info->toeplitz_random_given)
    write_into_file(outfile, "toeplitz-random", 0, 0 );
  if (args_info->toeplitz_save_random_given)
    write_into_file(outfile, "toeplitz-save-random", args_info->toeplitz_save_random_orig, 0);
  if (args_info->rhs_file_given)
    write_into_file(outfile, "rhs-file", args_info->rhs_file_orig, 0);
  if (args_info->rhs_random_given)
    write_into_file(outfile, "rhs-random", 0, 0 );
  if (args_info->rhs_save_random_given)
    write_into_file(outfile, "rhs-save-random", args_info->rhs_save_random_orig, 0);
  if (args_info->random_seed_given)
    write_into_file(outfile, "random-seed", args_info->random_seed_orig, 0);
  if (args_info->time_given)
    write_into_file(outfile, "time", 0, 0 );
  if (args_info->show_results_given)
    write_into_file(outfile, "show-results", 0, 0 );
  if (args_info->raw_results_given)
    write_into_file(outfile, "raw-results", 0, 0 );
  if (args_info->raw_headers_given)
    write_into_file(outfile, "raw-headers", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info_dtspg *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info_dtspg *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info_dtspg *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info_dtspg *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info_dtspg *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info_dtspg *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info_dtspg *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  
  /* checks for dependences among options */
  if (args_info->toeplitz_save_random_given && ! args_info->toeplitz_random_given)
    {
      fprintf (stderr, "%s: '--toeplitz-save-random' option depends on option 'toeplitz-random'%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  if (args_info->rhs_save_random_given && ! args_info->rhs_random_given)
    {
      fprintf (stderr, "%s: '--rhs-save-random' option depends on option 'rhs-random'%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info_dtspg *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info_dtspg local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "size",	1, NULL, 'n' },
        { "block-size",	1, NULL, 'z' },
        { "number-blocks",	1, NULL, 'b' },
        { "toeplitz-file",	1, NULL, 0 },
        { "toeplitz-random",	0, NULL, 0 },
        { "toeplitz-save-random",	1, NULL, 0 },
        { "rhs-file",	1, NULL, 0 },
        { "rhs-random",	0, NULL, 0 },
        { "rhs-save-random",	1, NULL, 0 },
        { "random-seed",	1, NULL, 0 },
        { "time",	0, NULL, 0 },
        { "show-results",	0, NULL, 0 },
        { "raw-results",	0, NULL, 0 },
        { "raw-headers",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVn:z:b:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'n':	/* Size of problem.  */
        
        
          if (update_arg( (void *)&(args_info->size_arg), 
               &(args_info->size_orig), &(args_info->size_given),
              &(local_args_info.size_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "size", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'z':	/* Block size.  */
        
        
          if (update_arg( (void *)&(args_info->block_size_arg), 
               &(args_info->block_size_orig), &(args_info->block_size_given),
              &(local_args_info.block_size_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "block-size", 'z',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Number of blocks.  */
        
        
          if (update_arg( (void *)&(args_info->number_blocks_arg), 
               &(args_info->number_blocks_orig), &(args_info->number_blocks_given),
              &(local_args_info.number_blocks_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "number-blocks", 'b',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* File containing toeplitz vector values (set to '-' to use standard input).  */
          if (strcmp (long_options[option_index].name, "toeplitz-file") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->toeplitz_file_arg), 
                 &(args_info->toeplitz_file_orig), &(args_info->toeplitz_file_given),
                &(local_args_info.toeplitz_file_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "toeplitz-file", '-',
                additional_error))
              goto failure;
          
          }
          /* Use random data of specified size as toeplitz vector.  */
          else if (strcmp (long_options[option_index].name, "toeplitz-random") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->toeplitz_random_flag), 0, &(args_info->toeplitz_random_given),
                &(local_args_info.toeplitz_random_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "toeplitz-random", '-',
                additional_error))
              goto failure;
          
          }
          /* File where random toeplitz data should be saved.  */
          else if (strcmp (long_options[option_index].name, "toeplitz-save-random") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->toeplitz_save_random_arg), 
                 &(args_info->toeplitz_save_random_orig), &(args_info->toeplitz_save_random_given),
                &(local_args_info.toeplitz_save_random_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "toeplitz-save-random", '-',
                additional_error))
              goto failure;
          
          }
          /* File containing rhs vector values (set to '-' to use standard input).  */
          else if (strcmp (long_options[option_index].name, "rhs-file") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->rhs_file_arg), 
                 &(args_info->rhs_file_orig), &(args_info->rhs_file_given),
                &(local_args_info.rhs_file_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "rhs-file", '-',
                additional_error))
              goto failure;
          
          }
          /* Use random data of specified size as rhs vector.  */
          else if (strcmp (long_options[option_index].name, "rhs-random") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->rhs_random_flag), 0, &(args_info->rhs_random_given),
                &(local_args_info.rhs_random_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "rhs-random", '-',
                additional_error))
              goto failure;
          
          }
          /* File where random rhs data should be saved.  */
          else if (strcmp (long_options[option_index].name, "rhs-save-random") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->rhs_save_random_arg), 
                 &(args_info->rhs_save_random_orig), &(args_info->rhs_save_random_given),
                &(local_args_info.rhs_save_random_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "rhs-save-random", '-',
                additional_error))
              goto failure;
          
          }
          /* Seed used to initialize random number generator (allows repeatable tests).  */
          else if (strcmp (long_options[option_index].name, "random-seed") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->random_seed_arg), 
                 &(args_info->random_seed_orig), &(args_info->random_seed_given),
                &(local_args_info.random_seed_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "random-seed", '-',
                additional_error))
              goto failure;
          
          }
          /* Show time spent in system resolution.  */
          else if (strcmp (long_options[option_index].name, "time") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->time_flag), 0, &(args_info->time_given),
                &(local_args_info.time_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "time", '-',
                additional_error))
              goto failure;
          
          }
          /* Print system solution vector to standard output.  */
          else if (strcmp (long_options[option_index].name, "show-results") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->show_results_flag), 0, &(args_info->show_results_given),
                &(local_args_info.show_results_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "show-results", '-',
                additional_error))
              goto failure;
          
          }
          /* Generates raw results for statistical graphics.  */
          else if (strcmp (long_options[option_index].name, "raw-results") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->raw_results_flag), 0, &(args_info->raw_results_given),
                &(local_args_info.raw_results_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "raw-results", '-',
                additional_error))
              goto failure;
          
          }
          /* Prints commented header (column info) for raw results.  */
          else if (strcmp (long_options[option_index].name, "raw-headers") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->raw_headers_flag), 0, &(args_info->raw_headers_given),
                &(local_args_info.raw_headers_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "raw-headers", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
